using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace FTD.Web.UI.aspx.ProjectM
{
    public partial class Rep_Count : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            DataTable dt = new DataTable();
            dt.Columns.Add("0");
            dt.Columns.Add("1");
            dt.Columns.Add("2");
            dt.Columns.Add("3");
            dt.Columns.Add("4");
            dt.Columns.Add("5");
            dt.Columns.Add("6");
            dt.Columns.Add("7");
            dt.Columns.Add("8");
            dt.Columns.Add("9");
            dt.Columns.Add("10");
            dt.Columns.Add("11");


            DataRow
              dr = dt.NewRow();
            dr[0] = "济南";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "1";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "-";
            dr[10] = "2";
            dr[11] = "-";
            dt.Rows.Add(dr);

            dr = dt.NewRow();
            dr[0] = "青岛";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "1";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "淄博";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "枣庄";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "1";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);

            dr = dt.NewRow();
            dr[0] = "东营";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "烟台";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "2";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "潍坊";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "2";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "济宁";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "3";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "泰安";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "2";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "威海";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "1";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "日照";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "1";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "莱芜";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "2";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "临沂";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "4";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);

            dr = dt.NewRow();
            dr[0] = "德州";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "2";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);


            dr = dt.NewRow();
            dr[0] = "德州";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "1";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "滨州";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "1";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "聊城";
            dr[1] = "1";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "菏泽";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "2";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "合计";
            dr[1] = "-";
            dr[2] = "-";
            dr[3] = "-";
            dr[4] = "-";
            dr[5] = "-";
            dr[6] = "-";
            dr[7] = "-";
            dr[8] = "-";
            dr[9] = "-";
            dr[10] = "-";
            dr[11] = "-";
            dt.Rows.Add(dr);

            GVData.DataSource = dt;
            GVData.DataBind();
        }
    }
}