using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace FTD.Web.UI.aspx.ProjectM
{
    public partial class UserSetRight : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            DataTable dt = new DataTable();
            dt.Columns.Add("0");
            dt.Columns.Add("1");
            dt.Columns.Add("2");
            dt.Columns.Add("3");
            dt.Columns.Add("4");


            DataRow
              dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "许宁宝";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "李易阳";
            dr[2] = "男";
            dr[3] = "中级级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "孙所如";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "许宁宝";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "李易阳";
            dr[2] = "男";
            dr[3] = "中级级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "孙所如";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "许宁宝";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "李易阳";
            dr[2] = "男";
            dr[3] = "中级级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "孙所如";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "许宁宝";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "李易阳";
            dr[2] = "男";
            dr[3] = "中级级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "孙所如";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
           
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "孙所如";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "许宁宝";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "李易阳";
            dr[2] = "男";
            dr[3] = "中级级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "孙所如";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "许宁宝";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "李易阳";
            dr[2] = "男";
            dr[3] = "中级级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            dr = dt.NewRow();
            dr[0] = "1";
            dr[1] = "孙所如";
            dr[2] = "男";
            dr[3] = "高级工程师";
            dr[4] = "技术部";
            dt.Rows.Add(dr);
            GVData.DataSource = dt;
            GVData.DataBind();
        }
    }
}