//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 编辑生成页面 的本地化字符串。
        /// </summary>
        internal static string EditPage {
            get {
                return ResourceManager.GetString("EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成页面 的本地化字符串。
        /// </summary>
        internal static string PubPage {
            get {
                return ResourceManager.GetString("PubPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置密码限制 的本地化字符串。
        /// </summary>
        internal static string PwdText {
            get {
                return ResourceManager.GetString("PwdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为空则不启用限制 的本地化字符串。
        /// </summary>
        internal static string PwdTextDesc {
            get {
                return ResourceManager.GetString("PwdTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷选项 的本地化字符串。
        /// </summary>
        internal static string SurveyItem {
            get {
                return ResourceManager.GetString("SurveyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投票详情 的本地化字符串。
        /// </summary>
        internal static string VoteDesc {
            get {
                return ResourceManager.GetString("VoteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面预览 的本地化字符串。
        /// </summary>
        internal static string VotePageShow {
            get {
                return ResourceManager.GetString("VotePageShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看投票 的本地化字符串。
        /// </summary>
        internal static string VoteShow {
            get {
                return ResourceManager.GetString("VoteShow", resourceCulture);
            }
        }
    }
}
