//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Member {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Member() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Member", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所在地区 的本地化字符串。
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生日 的本地化字符串。
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所在模型 的本地化字符串。
        /// </summary>
        internal static string CurrentModel {
            get {
                return ResourceManager.GetString("CurrentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱已被使用！ 的本地化字符串。
        /// </summary>
        internal static string EmailIsExis {
            get {
                return ResourceManager.GetString("EmailIsExis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文名称已被使用！ 的本地化字符串。
        /// </summary>
        internal static string FieldEnameIsUse {
            get {
                return ResourceManager.GetString("FieldEnameIsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段名已被使用！ 的本地化字符串。
        /// </summary>
        internal static string FieldIsUse {
            get {
                return ResourceManager.GetString("FieldIsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资金 的本地化字符串。
        /// </summary>
        internal static string Funds {
            get {
                return ResourceManager.GetString("Funds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员组名已存在！ 的本地化字符串。
        /// </summary>
        internal static string GroupNameIsExis {
            get {
                return ResourceManager.GetString("GroupNameIsExis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员组名已被使用！ 的本地化字符串。
        /// </summary>
        internal static string GroupNameIsUse {
            get {
                return ResourceManager.GetString("GroupNameIsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 积分 的本地化字符串。
        /// </summary>
        internal static string Integral {
            get {
                return ResourceManager.GetString("Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否禁用 的本地化字符串。
        /// </summary>
        internal static string IsDisable {
            get {
                return ResourceManager.GetString("IsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定 的本地化字符串。
        /// </summary>
        internal static string Islock {
            get {
                return ResourceManager.GetString("Islock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许发布 的本地化字符串。
        /// </summary>
        internal static string IsPub {
            get {
                return ResourceManager.GetString("IsPub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许搜索 的本地化字符串。
        /// </summary>
        internal static string IsSearch {
            get {
                return ResourceManager.GetString("IsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许会员自助升级 的本地化字符串。
        /// </summary>
        internal static string IsSelfUpgrade {
            get {
                return ResourceManager.GetString("IsSelfUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用 的本地化字符串。
        /// </summary>
        internal static string IsShow {
            get {
                return ResourceManager.GetString("IsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许访问 的本地化字符串。
        /// </summary>
        internal static string IsVisit {
            get {
                return ResourceManager.GetString("IsVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后登录 的本地化字符串。
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员数 的本地化字符串。
        /// </summary>
        internal static string MemberCount {
            get {
                return ResourceManager.GetString("MemberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员组 的本地化字符串。
        /// </summary>
        internal static string MemberGroup {
            get {
                return ResourceManager.GetString("MemberGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员模型 的本地化字符串。
        /// </summary>
        internal static string MemberModel {
            get {
                return ResourceManager.GetString("MemberModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员模型名称已存在！ 的本地化字符串。
        /// </summary>
        internal static string MemberModelNameIsExis {
            get {
                return ResourceManager.GetString("MemberModelNameIsExis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员状态 的本地化字符串。
        /// </summary>
        internal static string MemberState {
            get {
                return ResourceManager.GetString("MemberState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机 的本地化字符串。
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSN 的本地化字符串。
        /// </summary>
        internal static string MSN {
            get {
                return ResourceManager.GetString("MSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标模型 的本地化字符串。
        /// </summary>
        internal static string NewModel {
            get {
                return ResourceManager.GetString("NewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布 的本地化字符串。
        /// </summary>
        internal static string Pub {
            get {
                return ResourceManager.GetString("Pub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ 的本地化字符串。
        /// </summary>
        internal static string QQ {
            get {
                return ResourceManager.GetString("QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务介绍 的本地化字符串。
        /// </summary>
        internal static string ServerIntro {
            get {
                return ResourceManager.GetString("ServerIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string TrueName {
            get {
                return ResourceManager.GetString("TrueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁 的本地化字符串。
        /// </summary>
        internal static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改模型 的本地化字符串。
        /// </summary>
        internal static string UpdateModel {
            get {
                return ResourceManager.GetString("UpdateModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已被注册！ 的本地化字符串。
        /// </summary>
        internal static string UserIsExis {
            get {
                return ResourceManager.GetString("UserIsExis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问 的本地化字符串。
        /// </summary>
        internal static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮编 的本地化字符串。
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
