//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为所有资源查找重写当前线程的 CurrentUICulture 属性，
        ///   方法是使用此强类型资源类。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加日期 的本地化字符串。
        /// </summary>
        internal static string AddTime {
            get {
                return ResourceManager.GetString("AddTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加水印 的本地化字符串。
        /// </summary>
        internal static string AddWaterMark {
            get {
                return ResourceManager.GetString("AddWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告 的本地化字符串。
        /// </summary>
        internal static string Advertisement {
            get {
                return ResourceManager.GetString("Advertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告位 的本地化字符串。
        /// </summary>
        internal static string Advertising {
            get {
                return ResourceManager.GetString("Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升 的本地化字符串。
        /// </summary>
        internal static string Asc {
            get {
                return ResourceManager.GetString("Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商家 的本地化字符串。
        /// </summary>
        internal static string BusinessModel {
            get {
                return ResourceManager.GetString("BusinessModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string COPY {
            get {
                return ResourceManager.GetString("COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成 的本地化字符串。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建目录 的本地化字符串。
        /// </summary>
        internal static string CreateDirectory {
            get {
                return ResourceManager.GetString("CreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义表单 的本地化字符串。
        /// </summary>
        internal static string CustomForm {
            get {
                return ResourceManager.GetString("CustomForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除吗？ 的本地化字符串。
        /// </summary>
        internal static string DelConfirm {
            get {
                return ResourceManager.GetString("DelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除空目录 的本地化字符串。
        /// </summary>
        internal static string DelDirectory {
            get {
                return ResourceManager.GetString("DelDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件 的本地化字符串。
        /// </summary>
        internal static string DelFile {
            get {
                return ResourceManager.GetString("DelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量删除目录/文件 的本地化字符串。
        /// </summary>
        internal static string DelFileAll {
            get {
                return ResourceManager.GetString("DelFileAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降 的本地化字符串。
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string Describe {
            get {
                return ResourceManager.GetString("Describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在 的本地化字符串。
        /// </summary>
        internal static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退稿 的本地化字符串。
        /// </summary>
        internal static string FlowFail {
            get {
                return ResourceManager.GetString("FlowFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程步骤 的本地化字符串。
        /// </summary>
        internal static string FlowStep {
            get {
                return ResourceManager.GetString("FlowStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过 的本地化字符串。
        /// </summary>
        internal static string FlowSuccess {
            get {
                return ResourceManager.GetString("FlowSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 jquery-validationEngine-cn.js 的本地化字符串。
        /// </summary>
        internal static string formValidationLanguage {
            get {
                return ResourceManager.GetString("formValidationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 友情链接分类 的本地化字符串。
        /// </summary>
        internal static string FriendLinkClass {
            get {
                return ResourceManager.GetString("FriendLinkClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不推荐 的本地化字符串。
        /// </summary>
        internal static string IsRecommendOff {
            get {
                return ResourceManager.GetString("IsRecommendOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐 的本地化字符串。
        /// </summary>
        internal static string IsRecommendOn {
            get {
                return ResourceManager.GetString("IsRecommendOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不置顶 的本地化字符串。
        /// </summary>
        internal static string IsTopOff {
            get {
                return ResourceManager.GetString("IsTopOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置顶 的本地化字符串。
        /// </summary>
        internal static string IsTopOn {
            get {
                return ResourceManager.GetString("IsTopOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逻辑删除 的本地化字符串。
        /// </summary>
        internal static string LogicDel {
            get {
                return ResourceManager.GetString("LogicDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型分组 的本地化字符串。
        /// </summary>
        internal static string ModelGroup {
            get {
                return ResourceManager.GetString("ModelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        internal static string ModelOrder {
            get {
                return ResourceManager.GetString("ModelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核流程 的本地化字符串。
        /// </summary>
        internal static string ReviewFlow {
            get {
                return ResourceManager.GetString("ReviewFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程状态 的本地化字符串。
        /// </summary>
        internal static string ReviewFlowState {
            get {
                return ResourceManager.GetString("ReviewFlowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源 的本地化字符串。
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷调查 的本地化字符串。
        /// </summary>
        internal static string Survey {
            get {
                return ResourceManager.GetString("Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷调查选项 的本地化字符串。
        /// </summary>
        internal static string SurveyItem {
            get {
                return ResourceManager.GetString("SurveyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷投票结果 的本地化字符串。
        /// </summary>
        internal static string SurveyVote {
            get {
                return ResourceManager.GetString("SurveyVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示信息 的本地化字符串。
        /// </summary>
        internal static string TipMessage {
            get {
                return ResourceManager.GetString("TipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 闭 的本地化字符串。
        /// </summary>
        internal static string UploadClose {
            get {
                return ResourceManager.GetString("UploadClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件不能大于 的本地化字符串。
        /// </summary>
        internal static string UploadErr1 {
            get {
                return ResourceManager.GetString("UploadErr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传格式不正确 的本地化字符串。
        /// </summary>
        internal static string UploadExtErr {
            get {
                return ResourceManager.GetString("UploadExtErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此文件为系统禁止上传类型 的本地化字符串。
        /// </summary>
        internal static string UploadExtErr1 {
            get {
                return ResourceManager.GetString("UploadExtErr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已存在，请另外命名文件名后上传 的本地化字符串。
        /// </summary>
        internal static string UploadFileExistErr {
            get {
                return ResourceManager.GetString("UploadFileExistErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.只能上传 的本地化字符串。
        /// </summary>
        internal static string UploadMsg {
            get {
                return ResourceManager.GetString("UploadMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件 的本地化字符串。
        /// </summary>
        internal static string UploadMsg1 {
            get {
                return ResourceManager.GetString("UploadMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string UploadMsg2 {
            get {
                return ResourceManager.GetString("UploadMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成缩略图 的本地化字符串。
        /// </summary>
        internal static string UploadMsg3 {
            get {
                return ResourceManager.GetString("UploadMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注：生成的缩略图会与上传的图片保存在同一路径下，文件命名为:上传文件名+.gif,例如上传图片保存后的名称是“201001011122.jpg”,则缩略图为“201001011122.jpg.gif” 的本地化字符串。
        /// </summary>
        internal static string UploadMsg4 {
            get {
                return ResourceManager.GetString("UploadMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每个文件不能大于 的本地化字符串。
        /// </summary>
        internal static string UploadMsg5 {
            get {
                return ResourceManager.GetString("UploadMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传功能已关闭，请与管理员联系 的本地化字符串。
        /// </summary>
        internal static string UploadMsg6 {
            get {
                return ResourceManager.GetString("UploadMsg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要上传的文件 的本地化字符串。
        /// </summary>
        internal static string UploadMsg7 {
            get {
                return ResourceManager.GetString("UploadMsg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请不要关闭，文件正在上传······ 的本地化字符串。
        /// </summary>
        internal static string UploadMsg8 {
            get {
                return ResourceManager.GetString("UploadMsg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上 传 的本地化字符串。
        /// </summary>
        internal static string UploadSubmit {
            get {
                return ResourceManager.GetString("UploadSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string UserNo {
            get {
                return ResourceManager.GetString("UserNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投票 的本地化字符串。
        /// </summary>
        internal static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
