//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FriendLink {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FriendLink() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FriendLink", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为所有资源查找重写当前线程的 CurrentUICulture 属性，
        ///   方法是使用此强类型资源类。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 加粗 的本地化字符串。
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消推荐 的本地化字符串。
        /// </summary>
        internal static string CancelCommend {
            get {
                return ResourceManager.GetString("CancelCommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消审核 的本地化字符串。
        /// </summary>
        internal static string CancelLink {
            get {
                return ResourceManager.GetString("CancelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核链接 的本地化字符串。
        /// </summary>
        internal static string CheckLink {
            get {
                return ResourceManager.GetString("CheckLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类描述 的本地化字符串。
        /// </summary>
        internal static string ClassDesc {
            get {
                return ResourceManager.GetString("ClassDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类名称已被使用，不能删除！ 的本地化字符串。
        /// </summary>
        internal static string ClassIsUse {
            get {
                return ResourceManager.GetString("ClassIsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类名称 的本地化字符串。
        /// </summary>
        internal static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类名称已存在！ 的本地化字符串。
        /// </summary>
        internal static string ClassNameIsExis {
            get {
                return ResourceManager.GetString("ClassNameIsExis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击次数 的本地化字符串。
        /// </summary>
        internal static string ClickNum {
            get {
                return ResourceManager.GetString("ClickNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐 的本地化字符串。
        /// </summary>
        internal static string Commend {
            get {
                return ResourceManager.GetString("Commend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐链接 的本地化字符串。
        /// </summary>
        internal static string CommendLink {
            get {
                return ResourceManager.GetString("CommendLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败！ 的本地化字符串。
        /// </summary>
        internal static string DelFail {
            get {
                return ResourceManager.GetString("DelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除链接 的本地化字符串。
        /// </summary>
        internal static string DelLink {
            get {
                return ResourceManager.GetString("DelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功！ 的本地化字符串。
        /// </summary>
        internal static string DelSuccess {
            get {
                return ResourceManager.GetString("DelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示选项 的本地化字符串。
        /// </summary>
        internal static string DisplayOptions {
            get {
                return ResourceManager.GetString("DisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站介绍 的本地化字符串。
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字 的本地化字符串。
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属分类 的本地化字符串。
        /// </summary>
        internal static string LinkClass {
            get {
                return ResourceManager.GetString("LinkClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接颜色 的本地化字符串。
        /// </summary>
        internal static string LinkColor {
            get {
                return ResourceManager.GetString("LinkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接类型 的本地化字符串。
        /// </summary>
        internal static string LinkType {
            get {
                return ResourceManager.GetString("LinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未审 的本地化字符串。
        /// </summary>
        internal static string NoCheck {
            get {
                return ResourceManager.GetString("NoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站 Logo 的本地化字符串。
        /// </summary>
        internal static string WebLogo {
            get {
                return ResourceManager.GetString("WebLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站名称 的本地化字符串。
        /// </summary>
        internal static string WebName {
            get {
                return ResourceManager.GetString("WebName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站名称已存在！ 的本地化字符串。
        /// </summary>
        internal static string WebNameIsExis {
            get {
                return ResourceManager.GetString("WebNameIsExis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站长姓名 的本地化字符串。
        /// </summary>
        internal static string WebSiteName {
            get {
                return ResourceManager.GetString("WebSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站地址 的本地化字符串。
        /// </summary>
        internal static string WebUrl {
            get {
                return ResourceManager.GetString("WebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站地址已存在！ 的本地化字符串。
        /// </summary>
        internal static string WebUrlIsExis {
            get {
                return ResourceManager.GetString("WebUrlIsExis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已审 的本地化字符串。
        /// </summary>
        internal static string YesCheck {
            get {
                return ResourceManager.GetString("YesCheck", resourceCulture);
            }
        }
    }
}
