//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Model {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Model() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Model", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为所有资源查找重写当前线程的 CurrentUICulture 属性，
        ///   方法是使用此强类型资源类。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败,此字段名已经存在于模板表中! 的本地化字符串。
        /// </summary>
        internal static string AddDataBaseFiledMessage {
            get {
                return ResourceManager.GetString("AddDataBaseFiledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败,保存文件大小字段已经存在于模板表中! 的本地化字符串。
        /// </summary>
        internal static string AddDataBaseMessage {
            get {
                return ResourceManager.GetString("AddDataBaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败! 的本地化字符串。
        /// </summary>
        internal static string AddError {
            get {
                return ResourceManager.GetString("AddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败,请填写文件保存字段名称! 的本地化字符串。
        /// </summary>
        internal static string AddFiledErrorMessage {
            get {
                return ResourceManager.GetString("AddFiledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败,此字段名已经存在! 的本地化字符串。
        /// </summary>
        internal static string AddFiledMessage {
            get {
                return ResourceManager.GetString("AddFiledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加项目 的本地化字符串。
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功! 的本地化字符串。
        /// </summary>
        internal static string AddSucess {
            get {
                return ResourceManager.GetString("AddSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收的邮件地址 的本地化字符串。
        /// </summary>
        internal static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告统计 的本地化字符串。
        /// </summary>
        internal static string ADStatistics {
            get {
                return ResourceManager.GetString("ADStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告管理 的本地化字符串。
        /// </summary>
        internal static string AdvertisementManage {
            get {
                return ResourceManager.GetString("AdvertisementManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按权重随机显示 的本地化字符串。
        /// </summary>
        internal static string AdvertisingDisplayType1 {
            get {
                return ResourceManager.GetString("AdvertisingDisplayType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按权重优先显示 的本地化字符串。
        /// </summary>
        internal static string AdvertisingDisplayType2 {
            get {
                return ResourceManager.GetString("AdvertisingDisplayType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按顺序循环显示 的本地化字符串。
        /// </summary>
        internal static string AdvertisingDisplayType3 {
            get {
                return ResourceManager.GetString("AdvertisingDisplayType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用验证码 的本地化字符串。
        /// </summary>
        internal static string Authcode {
            get {
                return ResourceManager.GetString("Authcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本字段 的本地化字符串。
        /// </summary>
        internal static string BasicField {
            get {
                return ResourceManager.GetString("BasicField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        internal static string BeginTime {
            get {
                return ResourceManager.GetString("BeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用 的本地化字符串。
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景透明 的本地化字符串。
        /// </summary>
        internal static string cbFlashMode {
            get {
                return ResourceManager.GetString("cbFlashMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计点击数 的本地化字符串。
        /// </summary>
        internal static string cblIsClick {
            get {
                return ResourceManager.GetString("cblIsClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计浏览数 的本地化字符串。
        /// </summary>
        internal static string cblIsView {
            get {
                return ResourceManager.GetString("cblIsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否显示关闭标签 的本地化字符串。
        /// </summary>
        internal static string cbMoveShowCloseAD {
            get {
                return ResourceManager.GetString("cbMoveShowCloseAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多选 的本地化字符串。
        /// </summary>
        internal static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击数 的本地化字符串。
        /// </summary>
        internal static string ClickCount {
            get {
                return ResourceManager.GetString("ClickCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text列 的本地化字符串。
        /// </summary>
        internal static string ColumnText {
            get {
                return ResourceManager.GetString("ColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value列 的本地化字符串。
        /// </summary>
        internal static string ColumnValue {
            get {
                return ResourceManager.GetString("ColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反对数 的本地化字符串。
        /// </summary>
        internal static string CounterCount {
            get {
                return ResourceManager.GetString("CounterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反方投票页面显示名称 的本地化字符串。
        /// </summary>
        internal static string CounterName {
            get {
                return ResourceManager.GetString("CounterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        internal static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义设置 的本地化字符串。
        /// </summary>
        internal static string CustomizeSetting {
            get {
                return ResourceManager.GetString("CustomizeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库读取 的本地化字符串。
        /// </summary>
        internal static string DataBaseInput {
            get {
                return ResourceManager.GetString("DataBaseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sql语句： 的本地化字符串。
        /// </summary>
        internal static string DataBaseSql {
            get {
                return ResourceManager.GetString("DataBaseSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据表列表 的本地化字符串。
        /// </summary>
        internal static string DataBaseTableList {
            get {
                return ResourceManager.GetString("DataBaseTableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-cn 的本地化字符串。
        /// </summary>
        internal static string DateLang {
            get {
                return ResourceManager.GetString("DateLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期时间 的本地化字符串。
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始位置 的本地化字符串。
        /// </summary>
        internal static string ddlFloatPositionDesc {
            get {
                return ResourceManager.GetString("ddlFloatPositionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变速漂浮 的本地化字符串。
        /// </summary>
        internal static string ddlFloatType1 {
            get {
                return ResourceManager.GetString("ddlFloatType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匀速漂浮 的本地化字符串。
        /// </summary>
        internal static string ddlFloatType2 {
            get {
                return ResourceManager.GetString("ddlFloatType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上下漂浮 的本地化字符串。
        /// </summary>
        internal static string ddlFloatType3 {
            get {
                return ResourceManager.GetString("ddlFloatType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左右漂浮 的本地化字符串。
        /// </summary>
        internal static string ddlFloatType4 {
            get {
                return ResourceManager.GetString("ddlFloatType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 漂浮类型 的本地化字符串。
        /// </summary>
        internal static string ddlFloatTypeDesc {
            get {
                return ResourceManager.GetString("ddlFloatTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告位置 的本地化字符串。
        /// </summary>
        internal static string ddlMovePositionDesc {
            get {
                return ResourceManager.GetString("ddlMovePositionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左上 的本地化字符串。
        /// </summary>
        internal static string ddlPopPosition1 {
            get {
                return ResourceManager.GetString("ddlPopPosition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左下 的本地化字符串。
        /// </summary>
        internal static string ddlPopPosition2 {
            get {
                return ResourceManager.GetString("ddlPopPosition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右上 的本地化字符串。
        /// </summary>
        internal static string ddlPopPosition3 {
            get {
                return ResourceManager.GetString("ddlPopPosition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右下 的本地化字符串。
        /// </summary>
        internal static string ddlPopPosition4 {
            get {
                return ResourceManager.GetString("ddlPopPosition4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹出位置 的本地化字符串。
        /// </summary>
        internal static string ddlPopPositionDesc {
            get {
                return ResourceManager.GetString("ddlPopPositionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前置窗口 的本地化字符串。
        /// </summary>
        internal static string ddlPopType1 {
            get {
                return ResourceManager.GetString("ddlPopType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后置窗口 的本地化字符串。
        /// </summary>
        internal static string ddlPopType2 {
            get {
                return ResourceManager.GetString("ddlPopType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网页对话框 的本地化字符串。
        /// </summary>
        internal static string ddlPopType3 {
            get {
                return ResourceManager.GetString("ddlPopType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背投广告 的本地化字符串。
        /// </summary>
        internal static string ddlPopType4 {
            get {
                return ResourceManager.GetString("ddlPopType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版位尺寸 的本地化字符串。
        /// </summary>
        internal static string ddlSize {
            get {
                return ResourceManager.GetString("ddlSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货币 的本地化字符串。
        /// </summary>
        internal static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认设置 的本地化字符串。
        /// </summary>
        internal static string DefaultSetting {
            get {
                return ResourceManager.GetString("DefaultSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示类型 的本地化字符串。
        /// </summary>
        internal static string DisplayType {
            get {
                return ResourceManager.GetString("DisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移项目 的本地化字符串。
        /// </summary>
        internal static string DownItem {
            get {
                return ResourceManager.GetString("DownItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下拉列表 的本地化字符串。
        /// </summary>
        internal static string DropDown {
            get {
                return ResourceManager.GetString("DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项数据来源： 的本地化字符串。
        /// </summary>
        internal static string DropDownDataType {
            get {
                return ResourceManager.GetString("DropDownDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表（可选择多列） 的本地化字符串。
        /// </summary>
        internal static string DropDownList {
            get {
                return ResourceManager.GetString("DropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑器类型： 的本地化字符串。
        /// </summary>
        internal static string EditorType {
            get {
                return ResourceManager.GetString("EditorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定接收的email 的本地化字符串。
        /// </summary>
        internal static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任何人都可以查看 的本地化字符串。
        /// </summary>
        internal static string Everyone {
            get {
                return ResourceManager.GetString("Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动画上传 的本地化字符串。
        /// </summary>
        internal static string ExtenFileUpload {
            get {
                return ResourceManager.GetString("ExtenFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告内容设置--动画 的本地化字符串。
        /// </summary>
        internal static string ExtenFileUploadDesc {
            get {
                return ResourceManager.GetString("ExtenFileUploadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动画尺寸 的本地化字符串。
        /// </summary>
        internal static string ExtenFileUploadSize {
            get {
                return ResourceManager.GetString("ExtenFileUploadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段别名： 的本地化字符串。
        /// </summary>
        internal static string FieldAlias {
            get {
                return ResourceManager.GetString("FieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统预定义控件 的本地化字符串。
        /// </summary>
        internal static string FieldControls {
            get {
                return ResourceManager.GetString("FieldControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段管理 的本地化字符串。
        /// </summary>
        internal static string FieldManage {
            get {
                return ResourceManager.GetString("FieldManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属分组： 的本地化字符串。
        /// </summary>
        internal static string FileGroup {
            get {
                return ResourceManager.GetString("FileGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片上传 的本地化字符串。
        /// </summary>
        internal static string FileUploadControl1 {
            get {
                return ResourceManager.GetString("FileUploadControl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告内容设置--图片 的本地化字符串。
        /// </summary>
        internal static string FileUploadDesc {
            get {
                return ResourceManager.GetString("FileUploadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片尺寸 的本地化字符串。
        /// </summary>
        internal static string FileUploadSize {
            get {
                return ResourceManager.GetString("FileUploadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退回的操作名 的本地化字符串。
        /// </summary>
        internal static string FlowStepFail {
            get {
                return ResourceManager.GetString("FlowStepFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退回的状态 的本地化字符串。
        /// </summary>
        internal static string FlowStepFailState {
            get {
                return ResourceManager.GetString("FlowStepFailState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此步骤可操作的状态 的本地化字符串。
        /// </summary>
        internal static string FlowStepState {
            get {
                return ResourceManager.GetString("FlowStepState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过的操作名 的本地化字符串。
        /// </summary>
        internal static string FlowStepSuccess {
            get {
                return ResourceManager.GetString("FlowStepSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过的状态 的本地化字符串。
        /// </summary>
        internal static string FlowStepSuccessState {
            get {
                return ResourceManager.GetString("FlowStepSuccessState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单内容管理 的本地化字符串。
        /// </summary>
        internal static string FormContentManage {
            get {
                return ResourceManager.GetString("FormContentManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前台表单模板 的本地化字符串。
        /// </summary>
        internal static string FrontModelAdd {
            get {
                return ResourceManager.GetString("FrontModelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前台列表模板 的本地化字符串。
        /// </summary>
        internal static string FrontModelList {
            get {
                return ResourceManager.GetString("FrontModelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否复选 的本地化字符串。
        /// </summary>
        internal static string IsCheck {
            get {
                return ResourceManager.GetString("IsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用反方投票 的本地化字符串。
        /// </summary>
        internal static string IsCounter {
            get {
                return ResourceManager.GetString("IsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用： 的本地化字符串。
        /// </summary>
        internal static string IsEnable {
            get {
                return ResourceManager.GetString("IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否从页面上输入值 的本地化字符串。
        /// </summary>
        internal static string IsInputValue {
            get {
                return ResourceManager.GetString("IsInputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否在前台列表显示 的本地化字符串。
        /// </summary>
        internal static string IsListVisible {
            get {
                return ResourceManager.GetString("IsListVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用中立方投票 的本地化字符串。
        /// </summary>
        internal static string IsNeutral {
            get {
                return ResourceManager.GetString("IsNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否发布到前台 的本地化字符串。
        /// </summary>
        internal static string IsRelease {
            get {
                return ResourceManager.GetString("IsRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否要回复 的本地化字符串。
        /// </summary>
        internal static string IsReply {
            get {
                return ResourceManager.GetString("IsReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否审核 的本地化字符串。
        /// </summary>
        internal static string IsReview {
            get {
                return ResourceManager.GetString("IsReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否提交到后台 的本地化字符串。
        /// </summary>
        internal static string IsSaveDataBase {
            get {
                return ResourceManager.GetString("IsSaveDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否要评分 的本地化字符串。
        /// </summary>
        internal static string IsScore {
            get {
                return ResourceManager.GetString("IsScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否发送到指定的email 的本地化字符串。
        /// </summary>
        internal static string IsSendAdminEmail {
            get {
                return ResourceManager.GetString("IsSendAdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否发送到指定的手机 的本地化字符串。
        /// </summary>
        internal static string IsSendAdminPhone {
            get {
                return ResourceManager.GetString("IsSendAdminPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否将回复发送到会员email 的本地化字符串。
        /// </summary>
        internal static string IsSendUserEmail {
            get {
                return ResourceManager.GetString("IsSendUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否将回复发送到会员手机 的本地化字符串。
        /// </summary>
        internal static string IsSendUserPhone {
            get {
                return ResourceManager.GetString("IsSendUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用正方投票 的本地化字符串。
        /// </summary>
        internal static string IsSquare {
            get {
                return ResourceManager.GetString("IsSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员可以查看 的本地化字符串。
        /// </summary>
        internal static string IsUser {
            get {
                return ResourceManager.GetString("IsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否只有会员提交问题 的本地化字符串。
        /// </summary>
        internal static string IsUserAnswer {
            get {
                return ResourceManager.GetString("IsUserAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否只有会员才能评论 的本地化字符串。
        /// </summary>
        internal static string IsUserSubmit {
            get {
                return ResourceManager.GetString("IsUserSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否只能会员才能投票 的本地化字符串。
        /// </summary>
        internal static string IsUserVote {
            get {
                return ResourceManager.GetString("IsUserVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 js名称 的本地化字符串。
        /// </summary>
        internal static string jsName {
            get {
                return ResourceManager.GetString("jsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过期时间 的本地化字符串。
        /// </summary>
        internal static string LastTime {
            get {
                return ResourceManager.GetString("LastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属版位 的本地化字符串。
        /// </summary>
        internal static string lbAdvertisingId {
            get {
                return ResourceManager.GetString("lbAdvertisingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左 的本地化字符串。
        /// </summary>
        internal static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投票限制时间 的本地化字符串。
        /// </summary>
        internal static string LimitTime {
            get {
                return ResourceManager.GetString("LimitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的链接有误! 的本地化字符串。
        /// </summary>
        internal static string LinkErrorMessage {
            get {
                return ResourceManager.GetString("LinkErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表加文本框 的本地化字符串。
        /// </summary>
        internal static string ListAndText {
            get {
                return ResourceManager.GetString("ListAndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SysAdmin\\Configuraion\\Model\\List.xml 的本地化字符串。
        /// </summary>
        internal static string ListPath {
            get {
                return ResourceManager.GetString("ListPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大字符数： 的本地化字符串。
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义列表列: 的本地化字符串。
        /// </summary>
        internal static string ModelCustomCol {
            get {
                return ResourceManager.GetString("ModelCustomCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注：如果值中有从本模型的字段中读取值，则“{字段名称}”标识 的本地化字符串。
        /// </summary>
        internal static string ModelCustomColInfo {
            get {
                return ResourceManager.GetString("ModelCustomColInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列名称 的本地化字符串。
        /// </summary>
        internal static string ModelCustomColName {
            get {
                return ResourceManager.GetString("ModelCustomColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        internal static string ModelCustomColValue {
            get {
                return ResourceManager.GetString("ModelCustomColValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string ModelDescribe {
            get {
                return ResourceManager.GetString("ModelDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string ModelEnable {
            get {
                return ResourceManager.GetString("ModelEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属模型： 的本地化字符串。
        /// </summary>
        internal static string ModelField {
            get {
                return ResourceManager.GetString("ModelField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称： 的本地化字符串。
        /// </summary>
        internal static string ModelFieldGroupName {
            get {
                return ResourceManager.GetString("ModelFieldGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序： 的本地化字符串。
        /// </summary>
        internal static string ModelFieldGroupOrder {
            get {
                return ResourceManager.GetString("ModelFieldGroupOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度： 的本地化字符串。
        /// </summary>
        internal static string ModelFieldHieght {
            get {
                return ResourceManager.GetString("ModelFieldHieght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属模型 的本地化字符串。
        /// </summary>
        internal static string ModelFieldList {
            get {
                return ResourceManager.GetString("ModelFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示信息： 的本地化字符串。
        /// </summary>
        internal static string ModelFieldMessage {
            get {
                return ResourceManager.GetString("ModelFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项： 的本地化字符串。
        /// </summary>
        internal static string ModelFieldOption {
            get {
                return ResourceManager.GetString("ModelFieldOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每行显示项数： 的本地化字符串。
        /// </summary>
        internal static string ModelFieldOptionCount {
            get {
                return ResourceManager.GetString("ModelFieldOptionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0为全部显示在一行 的本地化字符串。
        /// </summary>
        internal static string ModelFieldOptionCountValue {
            get {
                return ResourceManager.GetString("ModelFieldOptionCountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段类型： 的本地化字符串。
        /// </summary>
        internal static string ModelFieldType {
            get {
                return ResourceManager.GetString("ModelFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度： 的本地化字符串。
        /// </summary>
        internal static string ModelFieldWidth {
            get {
                return ResourceManager.GetString("ModelFieldWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *便于在管理项目中显示,列如文章内容 的本地化字符串。
        /// </summary>
        internal static string ModelFiledAliasMessage {
            get {
                return ResourceManager.GetString("ModelFiledAliasMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定日期 的本地化字符串。
        /// </summary>
        internal static string ModelFiledAppointedTime {
            get {
                return ResourceManager.GetString("ModelFiledAppointedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中 的本地化字符串。
        /// </summary>
        internal static string ModelFiledCenter {
            get {
                return ResourceManager.GetString("ModelFiledCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表是否显示： 的本地化字符串。
        /// </summary>
        internal static string ModelFiledCoulumnEnable {
            get {
                return ResourceManager.GetString("ModelFiledCoulumnEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列宽 的本地化字符串。
        /// </summary>
        internal static string ModelFiledCoulumnWidth {
            get {
                return ResourceManager.GetString("ModelFiledCoulumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段表长度 的本地化字符串。
        /// </summary>
        internal static string ModelFiledDataLength {
            get {
                return ResourceManager.GetString("ModelFiledDataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅日期 的本地化字符串。
        /// </summary>
        internal static string ModelFiledDate {
            get {
                return ResourceManager.GetString("ModelFiledDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期和时间格式 的本地化字符串。
        /// </summary>
        internal static string ModelFiledDateOption {
            get {
                return ResourceManager.GetString("ModelFiledDateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期和时间 的本地化字符串。
        /// </summary>
        internal static string ModelFiledDateTime {
            get {
                return ResourceManager.GetString("ModelFiledDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否默认排序 的本地化字符串。
        /// </summary>
        internal static string ModelFiledDefaultOrder {
            get {
                return ResourceManager.GetString("ModelFiledDefaultOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认值： 的本地化字符串。
        /// </summary>
        internal static string ModelFiledDefaultValue {
            get {
                return ResourceManager.GetString("ModelFiledDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框长度： 的本地化字符串。
        /// </summary>
        internal static string ModelFiledImageWitdh {
            get {
                return ResourceManager.GetString("ModelFiledImageWitdh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否加链接 的本地化字符串。
        /// </summary>
        internal static string ModelFiledIsLink {
            get {
                return ResourceManager.GetString("ModelFiledIsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否排序 的本地化字符串。
        /// </summary>
        internal static string ModelFiledIsOrder {
            get {
                return ResourceManager.GetString("ModelFiledIsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否RSS字段： 的本地化字符串。
        /// </summary>
        internal static string ModelFiledIsRss {
            get {
                return ResourceManager.GetString("ModelFiledIsRss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否搜索条件： 的本地化字符串。
        /// </summary>
        internal static string ModelFiledIsSearch {
            get {
                return ResourceManager.GetString("ModelFiledIsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用上传 的本地化字符串。
        /// </summary>
        internal static string ModelFiledIsUpload {
            get {
                return ResourceManager.GetString("ModelFiledIsUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居左 的本地化字符串。
        /// </summary>
        internal static string ModelFiledLeft {
            get {
                return ResourceManager.GetString("ModelFiledLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写链接地址和参数 的本地化字符串。
        /// </summary>
        internal static string ModelFiledLinkUrl {
            get {
                return ResourceManager.GetString("ModelFiledLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对齐方式 的本地化字符串。
        /// </summary>
        internal static string ModelFiledListAlignment {
            get {
                return ResourceManager.GetString("ModelFiledListAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大值： 的本地化字符串。
        /// </summary>
        internal static string ModelFiledMaxValue {
            get {
                return ResourceManager.GetString("ModelFiledMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *后台录入时，在标题旁的提示信息 的本地化字符串。
        /// </summary>
        internal static string ModelFIledMessages {
            get {
                return ResourceManager.GetString("ModelFIledMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小值： 的本地化字符串。
        /// </summary>
        internal static string ModelFiledMinValue {
            get {
                return ResourceManager.GetString("ModelFiledMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *注：字段名由字母、数字、下划线组成，并且仅能字母开头，不以下划线结尾。 例如：Content &lt;br&gt;
        ///可以在模板中用数据源标签调用该字段内容，调用形式例如：&lt;br&gt;
        ///{KT.Field ID=&quot;数据源标签ID&quot; fieldname=&quot;Content&quot; /} 的本地化字符串。
        /// </summary>
        internal static string ModelFiledNameMessage {
            get {
                return ResourceManager.GetString("ModelFiledNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string ModelFiledNull {
            get {
                return ResourceManager.GetString("ModelFiledNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小数位数： 的本地化字符串。
        /// </summary>
        internal static string ModelFiledNumber {
            get {
                return ResourceManager.GetString("ModelFiledNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两者皆要 的本地化字符串。
        /// </summary>
        internal static string ModelFiledOrderAll {
            get {
                return ResourceManager.GetString("ModelFiledOrderAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只要升序 的本地化字符串。
        /// </summary>
        internal static string ModelFiledOrderAsc {
            get {
                return ResourceManager.GetString("ModelFiledOrderAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只要降序 的本地化字符串。
        /// </summary>
        internal static string ModelFiledOrderDesc {
            get {
                return ResourceManager.GetString("ModelFiledOrderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序链接 的本地化字符串。
        /// </summary>
        internal static string ModelFiledOrderLink {
            get {
                return ResourceManager.GetString("ModelFiledOrderLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序规则 的本地化字符串。
        /// </summary>
        internal static string ModelFiledOrderOption {
            get {
                return ResourceManager.GetString("ModelFiledOrderOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *序号越小，排在越前面 的本地化字符串。
        /// </summary>
        internal static string ModelFiledOrdersMessage {
            get {
                return ResourceManager.GetString("ModelFiledOrdersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （注：只能填数字） 的本地化字符串。
        /// </summary>
        internal static string ModelFiledRequierdNumber {
            get {
                return ResourceManager.GetString("ModelFiledRequierdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居右 的本地化字符串。
        /// </summary>
        internal static string ModelFiledRight {
            get {
                return ResourceManager.GetString("ModelFiledRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索框排序 的本地化字符串。
        /// </summary>
        internal static string ModelFiledSearchOrder {
            get {
                return ResourceManager.GetString("ModelFiledSearchOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索框长度 的本地化字符串。
        /// </summary>
        internal static string ModelFiledSearchWidth {
            get {
                return ResourceManager.GetString("ModelFiledSearchWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅时间 的本地化字符串。
        /// </summary>
        internal static string ModelFiledTime {
            get {
                return ResourceManager.GetString("ModelFiledTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前日期 的本地化字符串。
        /// </summary>
        internal static string ModelFiledToday {
            get {
                return ResourceManager.GetString("ModelFiledToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置浏览该字段的会员组： 的本地化字符串。
        /// </summary>
        internal static string ModelFiledUserGourp {
            get {
                return ResourceManager.GetString("ModelFiledUserGourp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置操作该字段角色 的本地化字符串。
        /// </summary>
        internal static string ModelFiledUserRole {
            get {
                return ResourceManager.GetString("ModelFiledUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用 的本地化字符串。
        /// </summary>
        internal static string ModelFileIsEnable {
            get {
                return ResourceManager.GetString("ModelFileIsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否必填： 的本地化字符串。
        /// </summary>
        internal static string ModelFileIsRequired {
            get {
                return ResourceManager.GetString("ModelFileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存字段的名称,由字母、数字、下划线组成，且仅能字母开头，不以下划线结尾 的本地化字符串。
        /// </summary>
        internal static string ModelFileSaveName {
            get {
                return ResourceManager.GetString("ModelFileSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否保存文件大小 的本地化字符串。
        /// </summary>
        internal static string ModelFileSaveSize {
            get {
                return ResourceManager.GetString("ModelFileSaveSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许大小 的本地化字符串。
        /// </summary>
        internal static string ModelFileSizt {
            get {
                return ResourceManager.GetString("ModelFileSizt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许类型 的本地化字符串。
        /// </summary>
        internal static string ModelFileType {
            get {
                return ResourceManager.GetString("ModelFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注：允许多个类型请用“|”号分割，如：JPG|GIF 的本地化字符串。
        /// </summary>
        internal static string ModelFileTypeMessage {
            get {
                return ResourceManager.GetString("ModelFileTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组名称 的本地化字符串。
        /// </summary>
        internal static string ModelGroupName {
            get {
                return ResourceManager.GetString("ModelGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型状态： 的本地化字符串。
        /// </summary>
        internal static string ModelIsEnable {
            get {
                return ResourceManager.GetString("ModelIsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表页面功能按钮设置： 的本地化字符串。
        /// </summary>
        internal static string ModelListButton {
            get {
                return ResourceManager.GetString("ModelListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;br&gt;
        ///&lt;b&gt;自定义功能&lt;/b&gt;,注：action={e}{(字段)(值)}{条件}例：?action={e}{(IsDel)(1)}{ID=20100816182738} 的本地化字符串。
        /// </summary>
        internal static string ModelListButtonSelfDefinedInfo {
            get {
                return ResourceManager.GetString("ModelListButtonSelfDefinedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮名称 的本地化字符串。
        /// </summary>
        internal static string ModelListButtonSelfDefinedName {
            get {
                return ResourceManager.GetString("ModelListButtonSelfDefinedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        internal static string ModelListButtonSelfDefinedValue {
            get {
                return ResourceManager.GetString("ModelListButtonSelfDefinedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列显示 的本地化字符串。
        /// </summary>
        internal static string ModelListColumnEnable {
            get {
                return ResourceManager.GetString("ModelListColumnEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 别名 的本地化字符串。
        /// </summary>
        internal static string ModelListFieldAlias {
            get {
                return ResourceManager.GetString("ModelListFieldAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段名 的本地化字符串。
        /// </summary>
        internal static string ModelListFieldName {
            get {
                return ResourceManager.GetString("ModelListFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属组 的本地化字符串。
        /// </summary>
        internal static string ModelListFiledGroup {
            get {
                return ResourceManager.GetString("ModelListFiledGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必填 的本地化字符串。
        /// </summary>
        internal static string ModelListFiledRequired {
            get {
                return ResourceManager.GetString("ModelListFiledRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string ModelListFiledSerach {
            get {
                return ResourceManager.GetString("ModelListFiledSerach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        internal static string ModelListFiledSys {
            get {
                return ResourceManager.GetString("ModelListFiledSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string ModelListFiledType {
            get {
                return ResourceManager.GetString("ModelListFiledType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表页面链接设置： 的本地化字符串。
        /// </summary>
        internal static string ModelListLink {
            get {
                return ResourceManager.GetString("ModelListLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;自定义链接&lt;/b&gt;,注：?Action={s}{(当前表字段)(操作符)(值)} ... [u或n] ....  {(当前表字段)(操作符)(值或其它表字段)} 的本地化字符串。
        /// </summary>
        internal static string ModelListLinkSelfDefinedInfo {
            get {
                return ResourceManager.GetString("ModelListLinkSelfDefinedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接名称 的本地化字符串。
        /// </summary>
        internal static string ModelListLinkSelfDefinedName {
            get {
                return ResourceManager.GetString("ModelListLinkSelfDefinedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接地址 的本地化字符串。
        /// </summary>
        internal static string ModelListLinkSelfDefinedUrl {
            get {
                return ResourceManager.GetString("ModelListLinkSelfDefinedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型描述： 的本地化字符串。
        /// </summary>
        internal static string ModelMemo {
            get {
                return ResourceManager.GetString("ModelMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型名称： 的本地化字符串。
        /// </summary>
        internal static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择模块： &lt;br&gt;*管理模块管理 的本地化字符串。
        /// </summary>
        internal static string ModelParseTemplate {
            get {
                return ResourceManager.GetString("ModelParseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义系统字段： 的本地化字符串。
        /// </summary>
        internal static string ModelSysField {
            get {
                return ResourceManager.GetString("ModelSysField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据表名称： 的本地化字符串。
        /// </summary>
        internal static string ModelTableName {
            get {
                return ResourceManager.GetString("ModelTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态值 的本地化字符串。
        /// </summary>
        internal static string ModelValue {
            get {
                return ResourceManager.GetString("ModelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多行文本（不支持HTML） 的本地化字符串。
        /// </summary>
        internal static string MuliLineText {
            get {
                return ResourceManager.GetString("MuliLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多行文本（支持HTML） 的本地化字符串。
        /// </summary>
        internal static string MuliLineTextHtml {
            get {
                return ResourceManager.GetString("MuliLineTextHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中立数 的本地化字符串。
        /// </summary>
        internal static string NeutralCount {
            get {
                return ResourceManager.GetString("NeutralCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中立方投票页面显示名称 的本地化字符串。
        /// </summary>
        internal static string NeutralName {
            get {
                return ResourceManager.GetString("NeutralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原文 的本地化字符串。
        /// </summary>
        internal static string NewsUrl {
            get {
                return ResourceManager.GetString("NewsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不用审核 的本地化字符串。
        /// </summary>
        internal static string NoReview {
            get {
                return ResourceManager.GetString("NoReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批注 的本地化字符串。
        /// </summary>
        internal static string Notation {
            get {
                return ResourceManager.GetString("Notation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此类型无版位参数设置 的本地化字符串。
        /// </summary>
        internal static string NullSetting {
            get {
                return ResourceManager.GetString("NullSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字 的本地化字符串。
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ../Configuraion/Model/ParseMode.xml 的本地化字符串。
        /// </summary>
        internal static string ParseModePath {
            get {
                return ResourceManager.GetString("ParseModePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码验证 的本地化字符串。
        /// </summary>
        internal static string PasswordCode {
            get {
                return ResourceManager.GetString("PasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定接收的手机 的本地化字符串。
        /// </summary>
        internal static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹出方式 的本地化字符串。
        /// </summary>
        internal static string PopType {
            get {
                return ResourceManager.GetString("PopType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单选 的本地化字符串。
        /// </summary>
        internal static string Radio {
            get {
                return ResourceManager.GetString("Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围 的本地化字符串。
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接目标 的本地化字符串。
        /// </summary>
        internal static string rbtlLinkTarget {
            get {
                return ResourceManager.GetString("rbtlLinkTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新窗口 的本地化字符串。
        /// </summary>
        internal static string rbtlLinkTarget1 {
            get {
                return ResourceManager.GetString("rbtlLinkTarget1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原窗口 的本地化字符串。
        /// </summary>
        internal static string rbtlLinkTarget2 {
            get {
                return ResourceManager.GetString("rbtlLinkTarget2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计连接路径 的本地化字符串。
        /// </summary>
        internal static string rbtlLinkType {
            get {
                return ResourceManager.GetString("rbtlLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相对路径 的本地化字符串。
        /// </summary>
        internal static string rbtlLinkType1 {
            get {
                return ResourceManager.GetString("rbtlLinkType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绝对路径 的本地化字符串。
        /// </summary>
        internal static string rbtlLinkType2 {
            get {
                return ResourceManager.GetString("rbtlLinkType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告类型 的本地化字符串。
        /// </summary>
        internal static string rbtlType {
            get {
                return ResourceManager.GetString("rbtlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示方式 的本地化字符串。
        /// </summary>
        internal static string rbtlWeight {
            get {
                return ResourceManager.GetString("rbtlWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按权重随机显示，权重越大显示机会越大 的本地化字符串。
        /// </summary>
        internal static string rbtlWeight1 {
            get {
                return ResourceManager.GetString("rbtlWeight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按权重优先显示，显示权重值最大的广告 的本地化字符串。
        /// </summary>
        internal static string rbtlWeight2 {
            get {
                return ResourceManager.GetString("rbtlWeight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按顺序循环显示，此方式仅对矩形横幅有效 的本地化字符串。
        /// </summary>
        internal static string rbtlWeight3 {
            get {
                return ResourceManager.GetString("rbtlWeight3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除项目 的本地化字符串。
        /// </summary>
        internal static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看回复信息类型 的本地化字符串。
        /// </summary>
        internal static string ReplyType {
            get {
                return ResourceManager.GetString("ReplyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 都要审核 的本地化字符串。
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核流程 的本地化字符串。
        /// </summary>
        internal static string ReviewFlow {
            get {
                return ResourceManager.GetString("ReviewFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择投票项 的本地化字符串。
        /// </summary>
        internal static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div&gt;名 称：{name}&amp;nbsp;&amp;nbsp;值：{value}&amp;nbsp;&amp;nbsp;&lt;input type=&apos;button&apos; class=&apos;AddBtn&apos; onclick=&quot;ListButton_Del(this,&apos;{name}|{value},&apos;,&apos;{objContainer}&apos;)&quot; value=&apos;删除&apos;&gt;&lt;/div&gt; 的本地化字符串。
        /// </summary>
        internal static string SelfDefinedListTemplate {
            get {
                return ResourceManager.GetString("SelfDefinedListTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div&gt;名 称：{name}&amp;nbsp;&amp;nbsp;值：{value}&amp;nbsp;&amp;nbsp;&lt;input type=&apos;button&apos; onclick=&apos;ListButton_Del(this,\&quot;{delContent}\&quot;,\&quot;{objContainer}\&quot;)&apos; value=&apos;删除&apos; class=&apos;AddBtn&apos;&gt;&lt;/div&gt; 的本地化字符串。
        /// </summary>
        internal static string SelfDefinedListTemplateJS {
            get {
                return ResourceManager.GetString("SelfDefinedListTemplateJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尺寸 的本地化字符串。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sql查询条件 的本地化字符串。
        /// </summary>
        internal static string SqlWhere {
            get {
                return ResourceManager.GetString("SqlWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持数 的本地化字符串。
        /// </summary>
        internal static string SquareCount {
            get {
                return ResourceManager.GetString("SquareCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正方投票页面显示名称 的本地化字符串。
        /// </summary>
        internal static string SquareName {
            get {
                return ResourceManager.GetString("SquareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理步骤 的本地化字符串。
        /// </summary>
        internal static string StepManage {
            get {
                return ResourceManager.GetString("StepManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP段过滤限制段 多个用|隔开 的本地化字符串。
        /// </summary>
        internal static string SubmitLimitIP {
            get {
                return ResourceManager.GetString("SubmitLimitIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单限制提交时间(秒) 的本地化字符串。
        /// </summary>
        internal static string SubmitLimitTime {
            get {
                return ResourceManager.GetString("SubmitLimitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论提交限制时间 的本地化字符串。
        /// </summary>
        internal static string SubmitLimitTimeComment {
            get {
                return ResourceManager.GetString("SubmitLimitTimeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简介 的本地化字符串。
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SysAdmin\\Configuraion\\Model\\SysField.xml 的本地化字符串。
        /// </summary>
        internal static string SysFieldPath {
            get {
                return ResourceManager.GetString("SysFieldPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表名 的本地化字符串。
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板管理 的本地化字符串。
        /// </summary>
        internal static string TemplateManage {
            get {
                return ResourceManager.GetString("TemplateManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单行文件 的本地化字符串。
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框输入 的本地化字符串。
        /// </summary>
        internal static string TextBoxInput {
            get {
                return ResourceManager.GetString("TextBoxInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本|值,文本|值 的本地化字符串。
        /// </summary>
        internal static string TextBoxInputValue {
            get {
                return ResourceManager.GetString("TextBoxInputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 在时间间隔内不重复弹出，设为0时总是弹出 的本地化字符串。
        /// </summary>
        internal static string TimeDesc {
            get {
                return ResourceManager.GetString("TimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间限制 的本地化字符串。
        /// </summary>
        internal static string TimeLimmit {
            get {
                return ResourceManager.GetString("TimeLimmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间间隔 的本地化字符串。
        /// </summary>
        internal static string TimeSplit {
            get {
                return ResourceManager.GetString("TimeSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告内容设置--代码 的本地化字符串。
        /// </summary>
        internal static string TxtADCode {
            get {
                return ResourceManager.GetString("TxtADCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告简介 的本地化字符串。
        /// </summary>
        internal static string TxtADIntro {
            get {
                return ResourceManager.GetString("TxtADIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告内容设置--文本 的本地化字符串。
        /// </summary>
        internal static string TxtADTextDesc {
            get {
                return ResourceManager.GetString("TxtADTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框高： 的本地化字符串。
        /// </summary>
        internal static string txtBoxHeight {
            get {
                return ResourceManager.GetString("txtBoxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框宽： 的本地化字符串。
        /// </summary>
        internal static string txtBoxWidth {
            get {
                return ResourceManager.GetString("txtBoxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击数 的本地化字符串。
        /// </summary>
        internal static string txtClickCount {
            get {
                return ResourceManager.GetString("txtClickCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左右边距 的本地化字符串。
        /// </summary>
        internal static string TxtCoupletLeft {
            get {
                return ResourceManager.GetString("TxtCoupletLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上边距 的本地化字符串。
        /// </summary>
        internal static string TxtCoupletTop {
            get {
                return ResourceManager.GetString("TxtCoupletTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告过期时间 的本地化字符串。
        /// </summary>
        internal static string txtExpiredTime {
            get {
                return ResourceManager.GetString("txtExpiredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度 的本地化字符串。
        /// </summary>
        internal static string txtHeight {
            get {
                return ResourceManager.GetString("txtHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高 的本地化字符串。
        /// </summary>
        internal static string TxtImgHeight {
            get {
                return ResourceManager.GetString("TxtImgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽 的本地化字符串。
        /// </summary>
        internal static string TxtImgWidth {
            get {
                return ResourceManager.GetString("TxtImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接提示 的本地化字符串。
        /// </summary>
        internal static string TxtLinkAlt {
            get {
                return ResourceManager.GetString("TxtLinkAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接地址 的本地化字符串。
        /// </summary>
        internal static string TxtLinkUrl {
            get {
                return ResourceManager.GetString("TxtLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭标签的颜色 的本地化字符串。
        /// </summary>
        internal static string TxtMoveCloseFontColor {
            get {
                return ResourceManager.GetString("TxtMoveCloseFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动平滑度 的本地化字符串。
        /// </summary>
        internal static string TxtMoveDelay {
            get {
                return ResourceManager.GetString("TxtMoveDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （取值在0.001至1之间） 的本地化字符串。
        /// </summary>
        internal static string TxtMoveDelayDesc {
            get {
                return ResourceManager.GetString("TxtMoveDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览数 的本地化字符串。
        /// </summary>
        internal static string txtViewCount {
            get {
                return ResourceManager.GetString("txtViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告内容设置--页面 的本地化字符串。
        /// </summary>
        internal static string TxtWebFileUrlDesc {
            get {
                return ResourceManager.GetString("TxtWebFileUrlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意：页面地址需要加上http:// 的本地化字符串。
        /// </summary>
        internal static string TxtWebFileUrlTitle {
            get {
                return ResourceManager.GetString("TxtWebFileUrlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告权重 的本地化字符串。
        /// </summary>
        internal static string txtWeight {
            get {
                return ResourceManager.GetString("txtWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 版位按权重（优先级、随机）显示时，此处设置的权重越大，该广告显示的机会就越多 的本地化字符串。
        /// </summary>
        internal static string txtWeightTitle {
            get {
                return ResourceManager.GetString("txtWeightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度 的本地化字符串。
        /// </summary>
        internal static string txtWidth {
            get {
                return ResourceManager.GetString("txtWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索界面范围 的本地化字符串。
        /// </summary>
        internal static string UiType {
            get {
                return ResourceManager.GetString("UiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上 的本地化字符串。
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败! 的本地化字符串。
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移项目 的本地化字符串。
        /// </summary>
        internal static string UpItem {
            get {
                return ResourceManager.GetString("UpItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员不用审核 的本地化字符串。
        /// </summary>
        internal static string UserNoReview {
            get {
                return ResourceManager.GetString("UserNoReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正则表达式： 的本地化字符串。
        /// </summary>
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示错误： 的本地化字符串。
        /// </summary>
        internal static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证规则： 的本地化字符串。
        /// </summary>
        internal static string ValidationTypes {
            get {
                return ResourceManager.GetString("ValidationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览数 的本地化字符串。
        /// </summary>
        internal static string ViewCount {
            get {
                return ResourceManager.GetString("ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投票数 的本地化字符串。
        /// </summary>
        internal static string VoteCount {
            get {
                return ResourceManager.GetString("VoteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合法IP允许投票次数 的本地化字符串。
        /// </summary>
        internal static string VoteIPCount {
            get {
                return ResourceManager.GetString("VoteIPCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0为不限制次数 的本地化字符串。
        /// </summary>
        internal static string VoteIPCountMessage {
            get {
                return ResourceManager.GetString("VoteIPCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投票项目 的本地化字符串。
        /// </summary>
        internal static string VoteItem {
            get {
                return ResourceManager.GetString("VoteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联ID 的本地化字符串。
        /// </summary>
        internal static string VoteNewsId {
            get {
                return ResourceManager.GetString("VoteNewsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权重 的本地化字符串。
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
