//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Orgin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Orgin() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Orgin", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为所有资源查找重写当前线程的 CurrentUICulture 属性，
        ///   方法是使用此强类型资源类。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加人 的本地化字符串。
        /// </summary>
        internal static string AddMan {
            get {
                return ResourceManager.GetString("AddMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加子行业 的本地化字符串。
        /// </summary>
        internal static string AddSonIndustry {
            get {
                return ResourceManager.GetString("AddSonIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加子地区 的本地化字符串。
        /// </summary>
        internal static string AddSonLocation {
            get {
                return ResourceManager.GetString("AddSonLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加子类别 的本地化字符串。
        /// </summary>
        internal static string AddSonSort {
            get {
                return ResourceManager.GetString("AddSonSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加时间 的本地化字符串。
        /// </summary>
        internal static string AddTime {
            get {
                return ResourceManager.GetString("AddTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件 的本地化字符串。
        /// </summary>
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所在大楼 的本地化字符串。
        /// </summary>
        internal static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商户名称 的本地化字符串。
        /// </summary>
        internal static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已删除邮件箱 的本地化字符串。
        /// </summary>
        internal static string DeleteBox {
            get {
                return ResourceManager.GetString("DeleteBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 送货范围 的本地化字符串。
        /// </summary>
        internal static string DeliverZome {
            get {
                return ResourceManager.GetString("DeliverZome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 草稿箱 的本地化字符串。
        /// </summary>
        internal static string DraftBox {
            get {
                return ResourceManager.GetString("DraftBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所在楼层 的本地化字符串。
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 树枝管理 的本地化字符串。
        /// </summary>
        internal static string HeadManage {
            get {
                return ResourceManager.GetString("HeadManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JPG|JPEG|GIF|BMP,5072 的本地化字符串。
        /// </summary>
        internal static string ImageSuffix {
            get {
                return ResourceManager.GetString("ImageSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行业名称 的本地化字符串。
        /// </summary>
        internal static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属行业 的本地化字符串。
        /// </summary>
        internal static string IndustryIn {
            get {
                return ResourceManager.GetString("IndustryIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行业 的本地化字符串。
        /// </summary>
        internal static string IndustryManage {
            get {
                return ResourceManager.GetString("IndustryManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string IntegralInit {
            get {
                return ResourceManager.GetString("IntegralInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人 的本地化字符串。
        /// </summary>
        internal static string LinkMan {
            get {
                return ResourceManager.GetString("LinkMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系电话 的本地化字符串。
        /// </summary>
        internal static string LinkTel {
            get {
                return ResourceManager.GetString("LinkTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地区名称 的本地化字符串。
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属地区 的本地化字符串。
        /// </summary>
        internal static string LocationIn {
            get {
                return ResourceManager.GetString("LocationIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地区 的本地化字符串。
        /// </summary>
        internal static string LocationManage {
            get {
                return ResourceManager.GetString("LocationManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        internal static string Look {
            get {
                return ResourceManager.GetString("Look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  查看 ▼  的本地化字符串。
        /// </summary>
        internal static string Lookx {
            get {
                return ResourceManager.GetString("Lookx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  标记为 ▼ 的本地化字符串。
        /// </summary>
        internal static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册会员 的本地化字符串。
        /// </summary>
        internal static string MemberGroupID {
            get {
                return ResourceManager.GetString("MemberGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商家会员模型 的本地化字符串。
        /// </summary>
        internal static string MemberModelID {
            get {
                return ResourceManager.GetString("MemberModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  移动到 ▼  的本地化字符串。
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消推荐 的本地化字符串。
        /// </summary>
        internal static string NoRecommend {
            get {
                return ResourceManager.GetString("NoRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消推荐到店铺 的本地化字符串。
        /// </summary>
        internal static string NoRecommend2 {
            get {
                return ResourceManager.GetString("NoRecommend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理操作 的本地化字符串。
        /// </summary>
        internal static string Operate {
            get {
                return ResourceManager.GetString("Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款方式 的本地化字符串。
        /// </summary>
        internal static string PayWay {
            get {
                return ResourceManager.GetString("PayWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质 保 期 的本地化字符串。
        /// </summary>
        internal static string QualityPeriod {
            get {
                return ResourceManager.GetString("QualityPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质保范围 的本地化字符串。
        /// </summary>
        internal static string QualityZome {
            get {
                return ResourceManager.GetString("QualityZome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件箱 的本地化字符串。
        /// </summary>
        internal static string ReceiveBox {
            get {
                return ResourceManager.GetString("ReceiveBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人 的本地化字符串。
        /// </summary>
        internal static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐到首页 的本地化字符串。
        /// </summary>
        internal static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐到店铺 的本地化字符串。
        /// </summary>
        internal static string Recommend2 {
            get {
                return ResourceManager.GetString("Recommend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册日期 的本地化字符串。
        /// </summary>
        internal static string RegisteTime {
            get {
                return ResourceManager.GetString("RegisteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起售数量 的本地化字符串。
        /// </summary>
        internal static string SaleAmount {
            get {
                return ResourceManager.GetString("SaleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已发送邮件箱 的本地化字符串。
        /// </summary>
        internal static string SendBox {
            get {
                return ResourceManager.GetString("SendBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发件人 的本地化字符串。
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送时间 的本地化字符串。
        /// </summary>
        internal static string SendTime {
            get {
                return ResourceManager.GetString("SendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店铺所有者 的本地化字符串。
        /// </summary>
        internal static string ShopMember {
            get {
                return ResourceManager.GetString("ShopMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店铺号 的本地化字符串。
        /// </summary>
        internal static string ShopNo {
            get {
                return ResourceManager.GetString("ShopNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别名称 的本地化字符串。
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属类别 的本地化字符串。
        /// </summary>
        internal static string SortIn {
            get {
                return ResourceManager.GetString("SortIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别 的本地化字符串。
        /// </summary>
        internal static string SortManage {
            get {
                return ResourceManager.GetString("SortManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供 货 期 的本地化字符串。
        /// </summary>
        internal static string SupportPeriod {
            get {
                return ResourceManager.GetString("SupportPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
